name: test
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: "Trigger value"
        required: true
        default: 'TRUE'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run one echo
      run: |
        echo '${{ github.event.inputs.name }}'
    - name: test
      run: |
        python3.9 main.py

